import type { Member } from './types';

const PLACEHOLDER = '/images/members/placeholder.svg';

export const members: Member[] = [
  {
    id: 'sarpanch',
    role: 'sarpanch',
    category: 'leadership',
    roleLabel: { mr: 'सरपंच', en: 'Sarpanch' },
    name: { mr: 'सौ. ज्योती विलास निकम', en: 'Smt. Jyoti Vilas Nikam' },
    phone: '+917822029166',
    tenureStart: '2022-11-01',
    tenureEnd: '2027-11-30',
    photo: '/images/members/sarpanch.jpg',
    order: 1,
  },
  {
    id: 'up-sarpanch',
    role: 'up-sarpanch',
    category: 'leadership',
    roleLabel: { mr: 'उपसरपंच', en: 'Up-Sarpanch' },
    name: { mr: 'श्री. ऋषिकेश धोंडू मोरे', en: 'Shri. Rishikesh Dhondu More' },
    phone: '+918169891600',
    tenureStart: '2022-11-01',
    tenureEnd: '2027-11-30',
    photo: PLACEHOLDER,
    order: 2,
  },
  {
    id: 'gram-sevak',
    role: 'gram-sevak',
    category: 'leadership',
    roleLabel: { mr: 'ग्रामपंचायत अधिकारी', en: 'Gram Panchayat Officer' },
    name: { mr: 'श्री. मयूरेश नितीन वाकडे', en: 'Shri. Mayuresh Nitin Wakade' },
    phone: '+919881154658',
    photo: '/images/members/gram-sevak.jpg',
    order: 3,
  },
  {
    id: 'clerk',
    role: 'clerk',
    category: 'staff',
    roleLabel: { mr: 'लिपिक', en: 'Clerk' },
    name: { mr: 'सौ. ममता मंगेश जाधव', en: 'Smt. Mamta Mangesh Jadhav' },
    phone: '+919325565747',
    photo: PLACEHOLDER,
    order: 4,
  },
  {
    id: 'operator',
    role: 'operator',
    category: 'staff',
    roleLabel: { mr: 'संगणक चालक', en: 'Computer Operator' },
    name: { mr: 'सौ. प्रिती रुपेश पाटणे', en: 'Smt. Priti Rupesh Paatne' },
    phone: '+919082891174',
    photo: PLACEHOLDER,
    order: 5,
  },
  {
    id: 'shipai',
    role: 'shipai',
    category: 'staff',
    roleLabel: { mr: 'शिपाई', en: 'Shipai' },
    name: { mr: 'श्री. संदेश श्रीधर साळुंखे', en: 'Shri. Sandesh Shreedhar Salunkhe' },
    phone: '+918080789174',
    photo: PLACEHOLDER,
    order: 6,
  },
  {
    id: 'mgnrega',
    role: 'mgnrega',
    category: 'staff',
    roleLabel: {
      mr: 'ग्राम रोजगार सेवक (MGNREGA)',
      en: 'Gram Rojgaar Sevak (MGNREGA)',
    },
    name: { mr: 'श्री. संभाजी तानाजी गोरगावकर', en: 'Shri. Sambhaji Tanaji Gorgaokar' },
    phone: '+918669059247',
    photo: PLACEHOLDER,
    order: 7,
  },
];
